local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.clipboard = "unnamedplus"
opt.shiftwidth = 2
opt.softtabstop = 2
opt.tabstop = 2
opt.expandtab = true
opt.smartcase = true
opt.ignorecase = true
opt.hlsearch = true
opt.incsearch = true
opt.confirm = true
opt.splitbelow = true
opt.splitright = true
opt.updatetime = 200
opt.timeoutlen = 400
opt.ttimeoutlen = 50
opt.scrolloff = 3
opt.sidescrolloff = 3
opt.signcolumn = "yes"
opt.termguicolors = true
opt.mouse = "a"
opt.undofile = true
opt.backup = false
opt.swapfile = false
opt.completeopt = { "menu", "menuone", "noselect", "fuzzy" }
